#!/usr/bin/env bash

# shellcheck disable=SC1090
# shellcheck disable=SC1091

set -x
TOOLBOX_UTILS_DIR=${TOOLBOX_UTILS_DIR:-toolbox/deps/toolbox-utils}
set +x

# Includes
. "${TOOLBOX_UTILS_DIR}/includes/init.sh"
. "${TOOLBOX_UTILS_DIR}/includes/util.sh"
. "${TOOLBOX_UTILS_DIR}/includes/log.sh"
. "${TOOLBOX_UTILS_DIR}/includes/exec.sh"

# Directory where playbook files are contained
TOOLBOX_ANSISTRANO_PLAYBOOK_DIR=${TOOLBOX_ANSISTRANO_PLAYBOOK_DIR:-toolbox/ansible}

# Ansible playbook filename
TOOLBOX_ANSISTRANO_PLAYBOOK=${TOOLBOX_ANSISTRANO_PLAYBOOK:-deployWithAnsistrano.yml}

# Directory to prepare artifact archive
TOOLBOX_ANSISTRANO_ARTIFACT_DIR=${TOOLBOX_ANSISTRANO_ARTIFACT_DIR:-../../.docroot}

# Artifact file
TOOLBOX_ANSISTRANO_ARTIFACT_FILE=${TOOLBOX_ANSISTRANO_ARTIFACT_FILE:-artifact.tar.gz}

# Deployment environment
TOOLBOX_ANSISTRANO_DEPLOY_ENVIRONMENT=${TOOLBOX_ANSISTRANO_DEPLOY_ENVIRONMENT:-}

# Ansible inventory (use 'hostname,' to deploy to the single host)
TOOLBOX_ANSISTRANO_INVENTORY=${TOOLBOX_ANSISTRANO_INVENTORY:-${TOOLBOX_ANSISTRANO_PLAYBOOK_DIR}/${TOOLBOX_ANSISTRANO_DEPLOY_ENVIRONMENT}.inventory.yaml}

# Ansistrano to deploy to
TOOLBOX_ANSISTRANO_DEPLOY_TO=${TOOLBOX_ANSISTRANO_DEPLOY_TO:-}

# Ansistrano deploy via
TOOLBOX_ANSISTRANO_DEPLOY_VIA=${TOOLBOX_ANSISTRANO_DEPLOY_VIA:-copy_unarchive}

# Path for Ansistrano to deploy from
# TODO: Update for absolute paths handling
TOOLBOX_ANSISTRANO_DEPLOY_FROM=${TOOLBOX_ANSISTRANO_DEPLOY_FROM:-${TOOLBOX_ANSISTRANO_ARTIFACT_DIR}/${TOOLBOX_ANSISTRANO_ARTIFACT_FILE}}

toolbox_run "Deploy the artifact with Ansistrano" \
  ansible-playbook "${TOOLBOX_ANSISTRANO_PLAYBOOK_DIR}/${TOOLBOX_ANSISTRANO_PLAYBOOK}" \
    -i "${TOOLBOX_ANSISTRANO_INVENTORY}" \
    -e ansistrano_deploy_to="${TOOLBOX_ANSISTRANO_DEPLOY_TO}" \
    -e ansistrano_deploy_from="${TOOLBOX_ANSISTRANO_DEPLOY_FROM}" \
    -e deploy_environment="${TOOLBOX_ANSISTRANO_DEPLOY_ENVIRONMENT}" \
    -e ansistrano_deploy_via="${TOOLBOX_ANSISTRANO_DEPLOY_VIA}"
